apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: virtual-kubelet-webhook-bind
  labels:
    app: virtual-kubelet-webhook-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: virtual-kubelet-webhook
subjects:
  - kind: ServiceAccount
    name: virtual-kubelet-webhook
    namespace: {{ .Release.Namespace }}
